groupName: acme.runos.com

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: ghcr.io/runos-official/clusteragent-dns
  tag: latest
  pullPolicy: Always

replicaCount: 1

nameOverride: "runos-cluster-agent"
fullnameOverride: "runos-cluster-agent"

service:
  type: ClusterIP
  port: 443

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

storage:
  size: 1Gi
  # storageClassName: ""  # Uncomment to specify a storage class

nodeSelector: {}

tolerations: []

affinity: {}