apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ include "example-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: 80
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
